version: "3.8"

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: todo_app_server
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.postgres
    container_name: todo_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_dev
    restart: unless-stopped

volumes:
  postgres_data:
